### ISSUE TITLE
Google Analytics ID

### ISSUE THREAD

**Issue by naoto0804** [Valkyrja3607/MaskDiffusion#1]
I can see the number of visitors to your website (https://valkyrja3607.github.io/MaskDiffusion/) because my Google Analytics ID is somehow [embedded](https://github.com/Valkyrja3607/MaskDiffusion/blob/gh-pages/index.html#L39) 😂. **It isn't a problem**, but I would like to let you know just in case. 

P.S.
Of course I read [the paper](https://arxiv.org/abs/2403.11194), what a simple yet effective idea!

**Comment by Valkyrja3607** [comment]
Sorry and thank you for letting me know!
I was referring to your site when I created it.
I'll fix it.

P.S.
I also read LayoutDM paper. Congratulations on your CVPR!
