### ISSUE TITLE
The work is cool! About ckpt

### ISSUE THREAD

**Issue by yingqichao** [Valkyrja3607/MaskDiffusion#2]
This work is cool and brings a lot of inspirations! I'm interested whether you could share checkpoints for me to do some zero-shot test. Thanks~

**Comment by Valkyrja3607** [comment]
Thank you for your interest. You can use [model_weights/feature_extractor.pth](https://github.com/Valkyrja3607/MaskDiffusion/blob/main/model_weights/feature_extractor.pth).
